import UserFooter from '@/layout/userLayout/UserFooter'
import UserNavbar from '@/layout/userLayout/UserNavbar'
import Head from 'next/head';
import React, { ReactNode } from 'react'
interface IUserLayout {
  children: ReactNode;
  title: string;
}
export default function UserLayout(props: IUserLayout) {
  return (
    <>
      <Head>
        <title>{"World class | " + props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserNavbar />
      {props.children}
      <UserFooter />
    </>
  )
}
